<Project Sdk="Microsoft.NET.Sdk.Web">

  <ItemGroup>
    <ProjectReference Include="..\BcReleasePlanPortal.Data\BcReleasePlanPortal.Data.csproj" />
    <ProjectReference Include="..\BcReleasePlanPortal.Domain\BcReleasePlanPortal.Domain.csproj" />
  </ItemGroup>

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

</Project>
