<Project Sdk="Microsoft.NET.Sdk.Worker">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UserSecretsId>dotnet-BcReleasePlanPortal.Worker-7d531b03-f738-48f8-953c-cb0979e3d56a</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="8.0.10">
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
      <PrivateAssets>all</PrivateAssets>
    </PackageReference>
    <PackageReference Include="Microsoft.Extensions.Hosting" Version="8.0.1" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\BcReleasePlanPortal.Ingest\BcReleasePlanPortal.Ingest.csproj" />
    <ProjectReference Include="..\BcReleasePlanPortal.Data\BcReleasePlanPortal.Data.csproj" />
    <ProjectReference Include="..\BcReleasePlanPortal.Domain\BcReleasePlanPortal.Domain.csproj" />
  </ItemGroup>
</Project>
