// <auto-generated />
using System;
using BcReleasePlanPortal.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BcReleasePlanPortal.Data.Migrations
{
    [DbContext(typeof(BcReleasePlanDbContext))]
    partial class BcReleasePlanDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.10");

            modelBuilder.Entity("BcReleasePlanPortal.Domain.ChangeEvent", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("DetectedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Field")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("NewValue")
                        .HasColumnType("TEXT");

                    b.Property<bool>("Notified")
                        .HasColumnType("INTEGER");

                    b.Property<string>("OldValue")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("RoadmapItemId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("RoadmapItemId", "DetectedAt");

                    b.ToTable("ChangeEvents");
                });

            modelBuilder.Entity("BcReleasePlanPortal.Domain.Customer", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("AppSourceApps")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Contacts")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("CustomExtensions")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Environments")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Flags")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Integrations")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ModulesInUse")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ReviewCadence")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("TenantId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Customers");
                });

            modelBuilder.Entity("BcReleasePlanPortal.Domain.CustomerItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("CustomerId")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset?>("DecidedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("DecidedBy")
                        .HasColumnType("TEXT");

                    b.Property<int>("Decision")
                        .HasColumnType("INTEGER");

                    b.Property<string>("MatchReasons")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("MatchScore")
                        .HasColumnType("INTEGER");

                    b.Property<string>("OverrideNl")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Owner")
                        .HasColumnType("TEXT");

                    b.Property<int>("Relevance")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("RoadmapItemId")
                        .HasColumnType("TEXT");

                    b.Property<string>("TargetWindow")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("RoadmapItemId");

                    b.HasIndex("CustomerId", "RoadmapItemId")
                        .IsUnique();

                    b.ToTable("CustomerItems");
                });

            modelBuilder.Entity("BcReleasePlanPortal.Domain.ImpactNote", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("ActionRequiredNl")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Author")
                        .HasColumnType("TEXT");

                    b.Property<int>("EffortBand")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset?>("ReviewedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("Risk")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("RoadmapItemId")
                        .HasColumnType("TEXT");

                    b.Property<string>("SummaryNl")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("WhyItMattersNl")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("RoadmapItemId")
                        .IsUnique();

                    b.ToTable("ImpactNotes");
                });

            modelBuilder.Entity("BcReleasePlanPortal.Domain.ReleasePlan", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("CustomerId")
                        .HasColumnType("TEXT");

                    b.Property<string>("DocumentPath")
                        .HasColumnType("TEXT");

                    b.Property<string>("PeriodLabel")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset?>("PublishedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("PublishedBy")
                        .HasColumnType("TEXT");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Version")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CustomerId");

                    b.ToTable("ReleasePlans");
                });

            modelBuilder.Entity("BcReleasePlanPortal.Domain.ReleasePlanLine", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("ActionNl")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("ChangeType")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Decision")
                        .HasColumnType("INTEGER");

                    b.Property<int>("EffortBand")
                        .HasColumnType("INTEGER");

                    b.Property<DateOnly?>("GaDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("Owner")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ReleasePlanId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("RoadmapItemId")
                        .HasColumnType("TEXT");

                    b.Property<int>("SortOrder")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SummaryNl")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("TitleNl")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ReleasePlanId");

                    b.HasIndex("RoadmapItemId");

                    b.ToTable("ReleasePlanLines");
                });

            modelBuilder.Entity("BcReleasePlanPortal.Domain.RoadmapItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<int>("ChangeType")
                        .HasColumnType("INTEGER");

                    b.Property<string>("DescriptionRaw")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("EnabledBy")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ExternalId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("FirstSeenAt")
                        .HasColumnType("TEXT");

                    b.Property<DateOnly?>("GaDate")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("LastSeenAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Modules")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("NeedsConfirmation")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ObjectsTouched")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PayloadHash")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateOnly?>("PreviewDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("Product")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Source")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset?>("SourceModifiedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<string>("TargetVersion")
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Url")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Source", "ExternalId")
                        .IsUnique();

                    b.ToTable("RoadmapItems");
                });

            modelBuilder.Entity("BcReleasePlanPortal.Domain.ChangeEvent", b =>
                {
                    b.HasOne("BcReleasePlanPortal.Domain.RoadmapItem", "RoadmapItem")
                        .WithMany("ChangeEvents")
                        .HasForeignKey("RoadmapItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("RoadmapItem");
                });

            modelBuilder.Entity("BcReleasePlanPortal.Domain.CustomerItem", b =>
                {
                    b.HasOne("BcReleasePlanPortal.Domain.Customer", "Customer")
                        .WithMany("Items")
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BcReleasePlanPortal.Domain.RoadmapItem", "RoadmapItem")
                        .WithMany()
                        .HasForeignKey("RoadmapItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Customer");

                    b.Navigation("RoadmapItem");
                });

            modelBuilder.Entity("BcReleasePlanPortal.Domain.ImpactNote", b =>
                {
                    b.HasOne("BcReleasePlanPortal.Domain.RoadmapItem", "RoadmapItem")
                        .WithMany()
                        .HasForeignKey("RoadmapItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("RoadmapItem");
                });

            modelBuilder.Entity("BcReleasePlanPortal.Domain.ReleasePlan", b =>
                {
                    b.HasOne("BcReleasePlanPortal.Domain.Customer", "Customer")
                        .WithMany()
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Customer");
                });

            modelBuilder.Entity("BcReleasePlanPortal.Domain.ReleasePlanLine", b =>
                {
                    b.HasOne("BcReleasePlanPortal.Domain.ReleasePlan", "ReleasePlan")
                        .WithMany("Lines")
                        .HasForeignKey("ReleasePlanId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ReleasePlan");
                });

            modelBuilder.Entity("BcReleasePlanPortal.Domain.Customer", b =>
                {
                    b.Navigation("Items");
                });

            modelBuilder.Entity("BcReleasePlanPortal.Domain.ReleasePlan", b =>
                {
                    b.Navigation("Lines");
                });

            modelBuilder.Entity("BcReleasePlanPortal.Domain.RoadmapItem", b =>
                {
                    b.Navigation("ChangeEvents");
                });
#pragma warning restore 612, 618
        }
    }
}
